[dev]
  command = "npm run start"
  targetPort = 5173 # Vite's default port
  port = 8888
  framework = "vite"

[build]
  functions = "netlify/functions/"

[functions.cron]
  schedule = "*/10 * * * *"