[functions]
directory = "netlify/functions/"

[functions.notifications]
schedule = "*/2 * * * *"

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200